### ISSUE TITLE
TypeError: Cannot index by location index with a non-integer key

### ISSUE THREAD

**Issue by anbai106** [zhijian-yang/SurrealGAN#10]
Hi,

I am running the software using the example data in the repository but got errors.

The code is here:
```
import pandas as pd
from SurrealGAN.Surreal_GAN_representation_learning import repetitive_representation_learning

train_data = pd.read_csv('/SurrealGAN/datasets/sample_data.csv')
output_dir = "/Downloads/surrealgan"
npattern = 3
final_saving_epoch = 1
max_epoch = 1
## two important hyperparamters
lam = 0.2
gamma = 6
repetition_number = 1  # number of repetitions (at least 20 repetition is need to give the most reliable and reproducible result)
data_fraction = 1 # fraction of data used in each repetition
repetitive_representation_learning(train_data, npattern, repetition_number, data_fraction, final_saving_epoch, output_dir,
    lr=0.0008, batchsize=120, verbose=False, lipschitz_k=0.5, covariate= None, start_repetition=0, lam=lam, gamma=gamma)
```

The error is:

> File "run_surrealgan.py", line 14, in <module>
>   repetitive_representation_learning(train_data, npattern, repetition_number, data_fraction, final_saving_epoch, output_dir,
> File "/surrealgan/lib/python3.8/site-packages/SurrealGAN/Surreal_GAN_representation_learning.py", line 131, in repetitive_representation_learning
>   r_indices, selected_model_dimension_corr, selected_model_difference_corr, dimension_corr, difference_corr, best_epoch, selected_model_dir = representation_result(output_dir, npattern, data, final_saving_epoch, saving_freq, repetition, covariate = covariate)
> File "/surrealgan/lib/python3.8/site-packages/SurrealGAN/Surreal_GAN_representation_learning.py", line 57, in representation_result
>   best_row = agreement_f.iloc[agreement_f['Rindices_corr'].idxmax()]
> File "/surrealgan/lib/python3.8/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
>   return self._getitem_axis(maybe_callable, axis=axis)
> File "/surrealgan/lib/python3.8/site-packages/pandas/core/indexing.py", line 1653, in _getitem_axis
>   raise TypeError("Cannot index by location index with a non-integer key")
> TypeError: Cannot index by location index with a non-integer key

I'm not sure whether this is related to the parameters I set, but the error is from "**best_row = agreement_f.iloc[agreement_f['Rindices_corr'].idxmax()]**"

Also, please correct the path in the Example code for the input data ("**sample_data.csv**")

Thanks

**Comment by anbai106** [comment]
Oh, I may find the problem: 

**raise Exception("At least 10 trained models are required (repetition number need to be at least 10)")**

**Comment by anbai106** [comment]
I think the problem is because of the minimum number for several parameters in the example, e.g., repetition_number, max_epoch. If the user is trying to run the example with minimum computational power before they apply the model to their real data, we should give some guidance for these parameters.

I increased the parameter (repetition_number = 20), but got another error: "`UnboundLocalError: local variable 'agreement_f' referenced before assignment"

**Comment by zhijian-yang** [comment]
When running the sample code, please ensure that both final_saving_epoch and repetition_number are set to values greater than 10,000 and 4, respectively, to prevent potential errors. I have updated the readme now.
